---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.7
  environment:
    TEST_PYPI_TOKEN: {from_secret: TEST_PYPI_TOKEN}
  commands:
  - git fetch
  - pip install twine pytest -e . -q
  - pytest
  - shore status
  - shore verify --tag "$DRONE_TAG" --update-check=ignore
  - shore bump git
  - echo "[testpypi]\nusername = __token__\npassword = $TEST_PYPI_TOKEN\n" >> ~/.pypirc
  - shore build setuptools
  #- shore publish pypi --test

- name: publish
  image: python:3.7
  environment:
    PYPI_TOKEN: {from_secret: PYPI_TOKEN}
  commands:
  - git checkout .
  - pip install twine -e . -q
  - shore verify --tag "$DRONE_TAG" --tag-check=require --update-check=ignore
  - git diff
  - echo "[pypi]\nusername = __token__\npassword = $PYPI_TOKEN\n" >> ~/.pypirc
  - shore publish pypi
  depends_on:
  - build
  when:
    event:
    - tag
