---
kind: pipeline
type: docker
name: default

steps:
- name: verify-and-trial-publish
  image: python:3.7
  environment:
    TEST_PYPI_TOKEN:
      from_secret: test_pypi_token
  commands:
    # install
  - git submodule update --init
  - vendor/nr-python-libs/bin/dev-install nr.databind nr.fs nr.proxy
  - pip install -e .
  - pip install twine

  # verify
  - shore -v verify --tag "$DRONE_TAG"

  # trial publish
  - echo "[testpypi]\nusername = __token__\npassword = $TEST_PYPI_TOKEN\n" >> ~/.pypirc
  - shore bump --ci
  - git diff
  - shore -v publish pypi --test

- name: trial-install
  image: python:3.7
  failure: ignore  # Until we have the dependencies on PyPI
  commands:
  - pip install --index-url https://test.pypi.org/simple/ shore
  - shore verify --tag "$DRONE_TAG"
  depends_on:
  - verify-and-trial-publish
