name: nr.shore
version: "0.0.17"
license: MIT
url: https://git.niklasrosenstein.com/NiklasRosenstein/shore
description: |
  Automates the heavy lifting of release and distribution management
  for pure Python packages.
author: Niklas Rosenstein <rosensteinniklas@gmail.com>

modulename: shore

requirements:
  - python ^2.7|^3.4
  - beautifulsoup4 ^4.8.1
  - click ^7.0
  - jinja2 ^2.11.1
  - nr.algo.graph ^0.0.1
  - nr.databind.core ~0.0.1
  - nr.databind.json ~0.0.1
  - nr.fs ^1.5.0
  - nr.pylang.utils ^0.0.1
  - nr.proxy ^0.0.1
  - requests ^2.22.0
  - packaging ^20.1
  - PyYAML ^5.1.0
  - termcolor ^1.1.0
  - twine

entrypoints:
  console_scripts:
    - shore = shore.__main__:_entry_point
  shore.core.plugins:
    - core = shore.plugins.core:CorePlugin
    - dev-install = shore.plugins.dev_install:DevInstallRenderer
    - pypi = shore.plugins.pypi:PypiPublisher
    - requirements-file = shore.plugins.requirements_file:RequirementsFileRenderer
    - setuptools = shore.plugins.setuptools:SetuptoolsRenderer

manifest:
  - include src/shore/templates/dev_install/dev-install
  - recursive-include src/shore/templates *.yaml *.py *.md
