package:
  name: pliz
  version: 0.1.0
  license: MIT
  url: https://git.niklasrosenstein.com/NiklasRosenstein/pliz
  description: |
    Automates the heavy lifting of release and distribution management
    for pure Python packages.
  author: Niklas Rosenstein <rosensteinniklas@gmail.com>
  use: [setuptools]

requirements:
  - python ^2.7|^3.4
  - beautifulsoup4 ^4.8.1
  - nr.databind ^0.0.1
  - nr.fs ^1.5.0
  - nr.proxy ^0.0.1
  - requests ^2.22.0
  - PyYAML ^5.1.0
  - termcolor ^1.1.0

entrypoints:
  console_scripts:
    - pliz = pliz.__main__:console_main
  pliz.core.plugins:
    - core = pliz.plugins.coreplugin:CorePlugin
    - devinstallscript = pliz.plugins.devinstallscript:DevInstallScriptRenderer
    - init = pliz.plugins.init:InitRenderer
    - setuptools = pliz.plugins.setuptools:SetuptoolsRenderer
